#!/bin/zsh

# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

# include .secrets if it exists
SECRETS="$HOME/.secrets"
if [ -f "$SECRETS" ]; then
  echo "Including secrets from $SECRETS"
  . $SECRETS
fi

# generic environment variables
add_to_path() {
  export PATH=$PATH:$1
}

export DOTFILES_DIR="$HOME/.config"
export SCRIPTS_DIR="$DOTFILES_DIR/i3/scripts"
export PROJECTS="$HOME/PROGRAMMERING/projects"
export LD_LIBRARY_PATH=$GOPATH/src/github.com/zubairhamed/canopus/openssl/
export GOROOT="/opt/homebrew/Cellar/go/1.17.6/libexec/"

add_to_path "/opt/homebrew/opt/llvm/bin"
add_to_path "$GOROOT/bin"
add_to_path "$GOPATH/bin"
add_to_path "$GOPATH/bin"
add_to_path "$HOME/bin:$HOME/.local/bin"
add_to_path "/snap/bin"
add_to_path "/opt/homebrew/bin"
add_to_path "/usr/bin"
# shortcuts
alias dk="docker kill $(docker ps -q)"
alias highlight="ack --passthru"
alias c="clear"
alias p="cd $PROJECTS"
alias py="python"
alias py3="python3"
alias vim="nvim"
alias sc="cd $SCRIPTS_DIR"
alias terminalBackground="gsettings set io.elementary.terminal.settings background $@"
alias gogit="cd $GOPATH/src/github.com"
alias plantuml="java -jar $HOME/PROGRAMMERING/plantuml/plantuml.jar $@"
# git shortcuts
alias gmne="gm --no-edit --no-ff $@"
alias gpt="git push && git push --tags"
alias tags="glo | grep -oP '(?<=tag: ).*(?=\))'"

# config files
alias secrets="$EDITOR $HOME/.secrets"
alias i3conf="atom $DOTFILES_DIR/i3"
alias makeconf="vim $DOTFILES_DIR/Makefile"
alias snippets="aa $HOME/.atom/snippets.cson"
alias zshrc="vim $DOTFILES_DIR/shell/zshrc"
alias profile="vim $DOTFILES_DIR/shell/profile"
alias nconf="vim $DOTFILES_DIR/nvim/init.lua"

# eza as ls replacement
alias ls="eza --icons --classify --colour=auto --sort=type --modified --created --git --binary --group"
alias la="ls -a"
alias ll="ls -al"

alias untar="tar -zxvf $@"

# network & postgres
alias fixnet="sudo systemctl restart NetworkManager.service"
alias pg="sudo -u postgres psql"

github-open() {
  uri="https://github.com/"$(git remote -v | grep -Pi $1 | grep -oPi '((?<=github.com:)|(?<=github.com/))\w*\/.*(?=\.git \(fetch\))')
  google-chrome $uri
}

prune_git() {
  git fetch -p &&
    git branch --merged >/tmp/merged-branches &&
    vim /tmp/merged-branches &&
    xargs git branch -d </tmp/merged-branches
}

# if [ -n "$ZSH_VERSION" ]; then
#   terminalBackground "rgba(37, 46, 50, 0.95)"
# fi

unalias z 2>/dev/null
