#!/bin/zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom
export force_color_prompt=yes
export DOTFILES_DIR=$HOME/.config/dotfiles

ZSH_THEME="robbyrussell"
plugins=(
    git
    zsh-autosuggestions
    colored-man-pages
    alias-tips
    zsh-syntax-highlighting
    history-substring-search
)

source $ZSH/oh-my-zsh.sh

# Source profile to ensure aliases take precedence over oh-my-zsh defaults
source $DOTFILES_DIR/shell/profile

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
