#!/bin/bash
SPOTIFY_PID=`pgrep spotify | head -1 | tail -1`

if [ $SPOTIFY_PID ]; then
  echo "<span font_desc=\"Font Awesome 5 Free Solid\">forward</span>"
fi

if [ $BLOCK_BUTTON == 1 ]; then
  DIRNAME=`dirname $0`
  $DIRNAME/spotify_exec Next
fi
