#!/bin/bash
raw=`cat /sys/class/backlight/intel_backlight/brightness`

if [ `pgrep redshift` ]; then
	icon="<span color='white'><b>🌙</b></span>"
	if [ $BLOCK_BUTTON == 1 ]; then
		pkill redshift
	fi
else
	if [ $BLOCK_BUTTON == 1 ]; then
		redshift&
	fi
	icon="<span color='white'><b>☀</b></span>"
fi
brightness=$((raw / 10 + 10))
echo "$icon $brightness%"
