#!/bin/bash
print_stats() {
	port=`netstat -tulpn | grep $1 | grep -oP ':\d+'`
	if [ $port != "" ]; then
		echo """
			<span color='$2'>┃</span> 
			<span color='$2'>$3</span> ⇄ 
			<b><span color='$2'>${port:1}</span></b> 
			<span color='$2'>┃</span>
		"""
	fi
}

get_output() {
	api=`print_stats "api" "#4286f4" "&#xf233;"`
	node=`print_stats "node" "#ffa72d" "&#xf3d3;"`
	if [ "$api" != "" ]; then
		echo "$api"
	fi
	if [ "$node" != "" ]; then
		echo "$node"
	fi
}

echo `get_output`