#!/bin/bash
TEMPLATE="<span color='%s'><b>%s</b></span>%s"
OUT=`printf "$TEMPLATE" "#f04c5c" "⏺" ""`

# Check online status
~/.config/i3/scripts/online > /dev/null
if [ $? -eq 0 ]; then
	OUT=`printf "$TEMPLATE" "white" "&#xf1eb;" ""`

	NETWORK_NAME=`iwgetid -r`
	if [ "$NETWORK_NAME" == "" ]; then 
		OUT=`printf "$TEMPLATE" "white" "&#xf233;" ""`
		NETWORK_NAME="Ethernet"
	fi
	# If the connected button is clicked, show the network name
	if [ "$BLOCK_BUTTON" == "1" ]; then
		OUT="$OUT: <span color='#fff'><i>$NETWORK_NAME</i></span>"
	fi
fi
echo "$OUT"

# Open network settings on right click
if [ "$BLOCK_BUTTON" == "3" ]; then
	nohup gnome-control-center network >/dev/null 2>&1
fi
