#!/bin/bash
add=""
if [ $BLOCK_BUTTON == 1 ]; then
	com.github.thejambi.dayjournal
fi

# hour=`date '+%H'`
# if (( $hour >= 22 )); then
# 	add=" Husk å skrive i dagboka! | "
# fi

DOT="<span color='#fff'><b>⌚</b></span>"
DATE=`date '+%d.%m.%Y - %H:%M'`
echo "$DOT $DATE"
