#!/bin/bash

SECRETS="$HOME/.secrets"
DOT="<span color='#f04c5c'><b>⏺</b></span> <span color='#fff'>toggl</span>"
BASE_URL="https://www.toggl.com/api/v8/time_entries"
START_NEW="$BASE_URL/start"
GET_CURRENT="$BASE_URL/current"

setup() {
  # exit on network failure
  ~/.config/i3/scripts/online > /dev/null
  if [ $? == 1 ]; then
    exit 0
  fi

  if [ -f "$SECRETS" ]; then
    . $SECRETS
  else
    exit 1
  fi
}

main () {
  fetch_current
  if [ "$CURRENT" == "null" ];then
    if [ "$BLOCK_BUTTON" == "1" ]; then
      start_new "Started from i3" 0
      echo "$DOT - <b><i>Started new time entry</i></b>"
    elif [ "$BLOCK_BUTTON" == "4" ] || [ "$BLOCK_BUTTON" == "5" ]; then
      fetch_latest
      desc=`echo $LATEST | jq -r '.description'`
      pid=`echo $LATEST | jq -r '.pid'`
      start_new $desc $pid
      echo "$DOT - <b><i>Resumed '$desc'</i></b>"
    else
      echo "$DOT"
    fi
  else
    if [ "$BLOCK_BUTTON" == "3" ]; then
      id=`echo $CURRENT | jq -r '.id'`
      stop_time_entry "$id"
      echo "$DOT - <b><i>Stopped the running time entry</i></b>"
    fi
    print_current
  fi
}

start_new() {
  curl -s -u "$TOGGL_API_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"time_entry":{"description":"'"$1"'","pid":'$2',"tags":["i3"],"created_with":"curl"}}' \
    -X POST "$START_NEW" > /dev/null
}

fetch_current() {
  CURRENT=`curl -s -u "$TOGGL_API_TOKEN" "$GET_CURRENT" | jq -r '.data'`
}

fetch_latest() {
  LATEST=`curl -s -u "$TOGGL_API_TOKEN" "$BASE_URL" | jq -r '.[-1]'`
}

stop_time_entry() {
  curl -s -u "$TOGGL_API_TOKEN" \
    -H "Content-Type: application/json" \
    -X GET "$BASE_URL/$1/stop" > /dev/null
}

print_current() {
  START=`echo "$CURRENT" | jq -r '.start'`
  DURATION=`echo "$CURRENT" | jq -r '.duration'`
  NOW=`date +%s`
  DURATION=$(($NOW+$DURATION))

  h=$(($DURATION/3600))
  m=$(($DURATION%3600/60))
  s=$(($DURATION%60))

  FORMATTED_DURATION=`formatted_time`
  BASE="$DOT $FORMATTED_DURATION"

  if [ "$BLOCK_BUTTON" == "1" ]; then

    DESC=`echo "$CURRENT" | jq -r '.description'`
    if [ $DESC == "null" ]; then
      DESC="Aktivitet uten navn"
    fi

  	echo "$BASE - <i>$DESC</i>"
  else
    echo "$BASE"
  fi
}

formatted_time() {
  if (( $h < 10 )); then
    h="0$h"
  fi
  if (( $m < 10 )); then
    m="0$m"
  fi
  if (( $s < 10 )); then
    s="0$s"
  fi
  echo "<b>$h:$m:$s</b>"
}

end_date=`date -I`
start_date=`date -d "$end_date -1 days" -I`

setup
main
fetch_latest
