#!/bin/bash

# exit on network failure
if [ "`iwgetid -r`" == "" ]; then
  exit 0
fi

DOT="<span color='#f04c5c'><b>⏺</b></span> <span color='#fff'>toggl</span>"

TOGGL_API_TOKEN="527c14e65d925bfa39fdf59c6fecf67c:api_token"
# of course this is not my real one, lol
START_NEW="https://www.toggl.com/api/v8/time_entries/start"
GET_CURRENT="https://www.toggl.com/api/v8/time_entries/current"

fetch_current() {
  CURRENT=`curl -u "$TOGGL_API_TOKEN" "$GET_CURRENT" | jq -r '.data'`
}

print_current() {
  START=`echo "$CURRENT" | jq -r '.start'`
  DURATION=`echo "$CURRENT" | jq -r '.duration'`
  NOW=`date +%s`
  DURATION=$(($NOW+$DURATION))

  h=$(($DURATION/3600))
  m=$(($DURATION%3600/60))
  s=$(($DURATION%60))

  FORMATTED_DURATION=`formatted_time`
  BASE="$DOT $FORMATTED_DURATION"

  if [ "$BLOCK_BUTTON" == "1" ]; then

    DESC=`echo "$CURRENT" | jq -r '.description'`
    if [ $DESC == "null" ]; then
      DESC="Aktivitet uten navn"
    fi

  	echo "$BASE - <i>$DESC</i>"
  else
    echo "$BASE"
  fi
}

formatted_time() {
  if (( $h < 10 )); then
    h="0$h"
  fi
  if (( $m < 10 )); then
    m="0$m"
  fi
  if (( $s < 10 )); then
    s="0$s"
  fi
  echo "<b>$h:$m:$s</b>"
}

fetch_current

if [ "$CURRENT" == "null" ];then
  if [ $BLOCK_BUTTON == 3 ]; then
    curl -u "$TOGGL_API_TOKEN" \
    	-H "Content-Type: application/json" \
    	-d '{"time_entry":{"description":"Started from i3","tags":["i3"],"created_with":"curl"}}' \
    	-X POST "$START_NEW"
  fi
  echo "$DOT"
else
  print_current
fi
