#!/bin/bash
NETWORK_NAME=`iwgetid -r`

DOT="<span color='%s'><b>⏺</b></span> %s"

if [ "$BLOCK_BUTTON" == "3" ]; then
	nohup gnome-control-center network >/dev/null 2>&1
elif [ "$NETWORK_NAME" == "" ]; then
	TEXT=`printf "$DOT" "#f04c5c" "Disconnected"`
	echo "$TEXT"
else
	TEXT=`printf "$DOT" "#73c990" "Connected"`
	if [ "$BLOCK_BUTTON" == "1" ]; then
		echo "$TEXT: <span color='#fff'><i>$NETWORK_NAME</i></span>"
	else
		echo "$TEXT"
	fi
fi
