#!/bin/bash

# exit on network failure
~/.config/i3/scripts/online > /dev/null
if [ $? == 1 ]; then
  exit 0
fi

where_am_i=`whereami -r`
lon=`echo $where_am_i | grep -oP '(?<=longitude": )[0-9\.-]*'`
lat=`echo $where_am_i | grep -oP '(?<=latitude": )[0-9\.-]*'`

result=`curl -s -X GET --header "Accept: application/json" "https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=$lat&lon=$lon"`

symbol=`echo $result | grep -oP '(?<=symbol_code":")\w*' | head -1`
case $symbol in
*clearsky*|*fair*)
  weather_unicode="f185"
  weather_color="#f4eb42"
  ;;
*cloudy*|*fog*)
  weather_unicode="f0c2"
  weather_color="gray"
  ;;
*rain*)
  weather_unicode="f043"
  weather_color="#2b9ee5"
  ;;
*thunder*)
  weather_unicode="f0e7"
  weather_color="#adba2c"
  ;;
*)
  weather_unicode="f128"
  weather_color="gray"
  ;;
esac

weather_symbol="<span color='$weather_color'><b>&#x$weather_unicode;</b></span>"
temperature=`echo $result | grep -oP '(?<=air_temperature":)[0-9\.-]*' | head -1`
echo "$weather_symbol $temperature °C"
